apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nlz4uo2r9-python
  janus-idp.io/tekton: nlz4uo2r9-python
  backstage.io/kubernetes-id: nlz4uo2r9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nlz4uo2r9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
